[package]
name = "slicer-project-generator-bambu-studio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "AGPL-3.0-only"
publish = false
autobins = false

[dependencies]
zip = { version = "7.2.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }
anyhow = "1.0.100"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_jcs = "0.2.0"
sha2 = "0.11.0"
thiserror = "2.0.17"
roxmltree = "0.21.1"

[dev-dependencies]
quick-xml = "0.41.0"

[lib]
name = "slicer_project_generator_bambu_studio"
path = "src/lib.rs"

[[bin]]
name = "slicer-project-generator-bambu-studio"
path = "src/main.rs"
